name: Build prime kernel

on:
  workflow_dispatch:
    inputs:
      release:
          description: 'Upload release'
          type: boolean
          required: true
          default: false
      changelog:
          description: 'Changelog'
          type: string
          required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      release_ts: ${{ steps.ts.outputs.release_ts }}

    steps:
      - name: Generate release date
        id: ts
        run: |
          RELEASE_TS=$(date +'%Y%m%d-%H%M%S')
          echo "release_ts=$RELEASE_TS" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    outputs:
      release_ts: ${{ steps.ts.outputs.release_ts }}
    needs: prepare

    strategy:
      matrix:
        device:
          - { name: a71, device2: a71xxx, soc: sdmmagpie }
          - { name: a70q, device2: a70, soc: sm6150 }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 1

      - name: Install build tools
        run: |
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip \
            zstd

      - name: Download latest Google clang
        run: |
          wget -O llvm.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-r596125.tar.gz
          mkdir llvm-22; cd llvm-22
          tar -xf ../llvm.tar.gz
          rm ../llvm.tar.gz
          cd ..

      - name: Build kernel
        run: |
          chmod +x build.sh
          bash build.sh \
            "${{ matrix.device.name }}" \
            "${{ matrix.device.device2 }}" \
            "${{ matrix.device.soc }}"

      - name: Generate release notes
        if: matrix.device.name == 'a71'
        run: |
          : > version.txt
          echo "**Kernel version:** $(cat out/include/config/kernel.release)  " >> version.txt
          echo >> version.txt
          export KHASH="$(git rev-parse HEAD)"
          echo "**Kernel source:** [$KHASH](https://github.com/UN1CA/kernel_samsung_sm7150/tree/$KHASH)" >> version.txt

          if [ "${{ github.event.inputs.release }}" = "true" ] && \
             [ -n "${{ github.event.inputs.changelog }}" ]; then
            echo >> version.txt
            echo "**Changelog:**" >> version.txt
            echo >> version.txt
            printf "%b\n" "${{ github.event.inputs.changelog }}" >> version.txt
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: PrimeKernel-${{ matrix.device.name }}-${{ needs.prepare.outputs.release_ts }}
          path: AnyKernel3/

      - name: Upload release notes
        if: matrix.device.name == 'a71'
        uses: actions/upload-artifact@v5
        with:
          name: release-notes
          path: version.txt
          retention-days: 1

  release:
    needs: [prepare, build]
    if: github.event.inputs.release == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Zip build artifacts
        run: |
          cd artifacts
          for dir in PrimeKernel-*; do
            (
              cd "$dir"
              zip -r "../${dir}.zip" .
            )
          done

      - name: Download release version
        uses: actions/download-artifact@v4
        with:
          name: release-notes
          path: ./

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          body_path: version.txt
          tag_name: "${{ needs.prepare.outputs.release_ts }}"
          name: "PrimeKernel-${{ needs.prepare.outputs.release_ts }}"
          files: artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
