name: Build paradigm kernel

on:
  workflow_dispatch:
    inputs:
      release:
          description: 'Upload release'
          type: boolean
          required: true
          default: false
      changelog:
          description: 'Changelog'
          type: string
          required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository with submodules (shallow clone)
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 1

      - name: Install build tools
        run: |
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip \
            zstd

      - name: Download prebuilt Google clang
        run: |
          wget -O llvm.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-r596125.tar.gz
          mkdir llvm-22; cd llvm-22
          tar -xf ../llvm.tar.gz
          rm ../llvm.tar.gz
          cd ..

      # 2. Run your custom bash script
      - name: Build kernel
        run: |
          chmod +x build.sh
          bash build.sh

      - name: Generate release version
        id: ts
        run: |
          echo "RELEASE_TS=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
          : > version.txt
          echo "**Kernel version:** $(cat out/include/config/kernel.release)  " >> version.txt
          echo >> version.txt
          export KHASH="$(git rev-parse HEAD)"
          echo "**Kernel source:** [$KHASH](https://github.com/UN1CA/kernel_samsung_sm7150/tree/$KHASH)" >> version.txt

          if [ "${{ github.event.inputs.release }}" = "true" ] && \
             [ -n "${{ github.event.inputs.changelog }}" ]; then
            echo >> version.txt
            echo "**Changelog:**" >> version.txt
            echo >> version.txt
            printf "%b\n" "${{ github.event.inputs.changelog }}" >> version.txt
          fi

      # 3. Upload the generated boot.img
      - name: Upload release assets
        if: github.event.inputs.release
        uses: softprops/action-gh-release@v2.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          body_path: version.txt
          tag_name: "${{ env.RELEASE_TS }}"
          name: "ParadigmKernel-${{ env.RELEASE_TS }}"
          files: |
            boot.img
            dtbo.img
